# Generated by Django 3.1.7 on 2021-02-23 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estaciOmediambiental', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='estatic',
        ),
        migrations.AddField(
            model_name='client',
            name='localitzacio',
            field=models.TextField(default=None, verbose_name=''),
        ),
        migrations.AddField(
            model_name='registre',
            name='client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='estaciOmediambiental.client', verbose_name=''),
        ),
        migrations.AddField(
            model_name='registre',
            name='sensor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='estaciOmediambiental.sensor', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='estaciOmediambiental.client', verbose_name=''),
        ),
    ]
