# Generated by Django 3.1.7 on 2021-02-23 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estaciOmediambiental', '0002_auto_20210223_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registre',
            name='client',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='estaciOmediambiental.client', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='registre',
            name='sensor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='estaciOmediambiental.sensor', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='client',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='estaciOmediambiental.client', verbose_name=''),
        ),
    ]
